version: 0.2

env:
  variables:
    APP_SETTINGS: "testing"
    TEST_STATIC_BEARER_TOKEN: "test-token-123"
    TEST_DATABASE_URL: "sqlite:///:memory:"
    AWS_DEFAULT_REGION: "us-east-2"
    ECR_REPOSITORY_NAME: "blacklist-microservice"
    CONTAINER_NAME: "blacklist-microservice" 

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependencias..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Ejecutando pruebas unitarias..."
      - python -m pytest tests/ -v
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo "Generando imagen Docker..."
      - docker build -t $ECR_REPOSITORY_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $ECR_REPOSITORY_NAME:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Subiendo imagen a ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo "Generando imagedefinitions.json..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - taskdef.json
  name: blacklist-microservice-artifact